%YAML:1.0
Camera.fx: 460.0
Camera.fy: 460.0
Camera.cx: 320.0
Camera.cy: 240.0
Camera.k1: 0
Camera.k2: 0
Camera.p1: 0
Camera.p2: 0
Camera.k3: 0
Camera.fps: 25.0
Camera.RGB: 0
ORBextractor.nFeatures: 1500
ORBextractor.scaleFactor: 1.3
ORBextractor.nLevels: 6
ORBextractor.iniThFAST: 25
ORBextractor.minThFAST: 10
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.5
Viewer.ViewpointZ: -1.5
Viewer.ViewpointF: 460
